### ISSUE TITLE
Request to evaluate the new O1 model by OpenAI (longer context + API now available)

### ISSUE THREAD

**Issue by Belzedar94** [marzenakrp/nocha#2]
Request in title :)

Love your work!!

**Comment by marzenakrp** [comment]
Yup, we are working on it :) Also thank you!

**Comment by marzenakrp** [comment]
we kinda added it, a bit disappointing for the price we had to pay :(

**Comment by David-Lee-1990** [comment]
deepseek R1?

**Comment by marzenakrp** [comment]
Yup, looking at it but API (that handles long CTX) is pricey so will need to wait for more gpus before we can run it :)

**Comment by marzenakrp** [comment]
R1 was finally added :)
